In [ ]:
# installing the numpy
!pip install numpy

In [2]:
# importing numpy

import numpy as np  # package can be called using "np" as its alias

In [3]:
# list to numpy array

lst = ['abc', 'def', 'ghi', 'jkl']

arr = np.array(lst)

print(type(arr))
print(arr)

<class 'numpy.ndarray'>
['abc' 'def' 'ghi' 'jkl']


In [6]:
# arrays

# arrays is of homogenous structure, will only contain the same datatype
# list with different datatype elements will be converted to same type
# same type will be determined by the possible datatype that all the elements of list can adapt

lst = [1,2,3,4,'a','b']   # lst contains int and string data types

arr = np.array(lst)       # changing to array will conver int into string because we cant cast string into int

print(type(arr))
print(arr)
print(type(arr[1]))

<class 'numpy.ndarray'>
['1' '2' '3' '4' 'a' 'b']
<class 'numpy.str_'>


In [10]:
# datatype

# array has multiple datatype even for a integer datatype

lst = [1,2,3, 4, 5]

arr = np.array(lst)

print(arr)
print(type(arr[1]))

# We can change the datatype of element from int64 to other datatype like int8
print("Converting int64 datatype into int8 datatype")

arr1 = np.array(lst, dtype = np.int8)

print(arr1)
print(type(arr1[1]))

arr2 = np.array(lst, dtype = np.float64)

print(arr2)
print(type(arr2[1]))

[1 2 3 4 5]
<class 'numpy.int64'>
Converting int64 datatype into int8 datatype
[1 2 3 4 5]
<class 'numpy.int8'>
[1. 2. 3. 4. 5.]
<class 'numpy.float64'>


In [13]:
# numpy.arange(start, stop, step)

# similar to range() function
# returns ndarray type

arr = np.arange(1,10,2)

print(arr)
print(type(arr))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [15]:
# np.linspace(start, stop, num = x)

# linspace will give x number of equally spaced numbers between start and stop point
# returns the ndarray of float elements

arr = np.linspace(1,10,5)
print(arr)

print(arr[1]-arr[0])
print(arr[2]-arr[1])
print(arr[3]-arr[2])
print(arr[4]-arr[3])


[ 1.    3.25  5.5   7.75 10.  ]
2.25
2.25
2.25
2.25


In [ ]:
# 1 DIMENSIONAL ARRAY OR LIST

# [1, 2, 3, 4, 5]

# 2 DIMENSIONAL ARRAY OR LIST

# [[1, 2, 3], [4, 5, 6], [7, 8, 9]]        OR     [[1, 2, 3],
#                                                  [4, 5, 6],
#                                                  [7, 8, 9]]

# 3 DIMENSION ARRAY OR LIST

# [[[1, 2, 3], [4,5]],[6,7,8]]  OR     [[[1, 2, 3],
#                                         [4,5]],
#                                         [6, 7, 8]]


In [26]:
# numpy.zeros(shape)

# this function will create a ndarray of zeros in dimension shape of shape paramenter

print(np.zeros(5))
print()
dim3 = np.zeros((4,3,2))
print(dim3)

print()
print("DIMENSION",dim3.ndim)   # used to find the dimension of the ndarray
print("SHAPE    ",dim3.shape)  # used to find the shape of the ndarray

[0. 0. 0. 0. 0.]

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]

DIMENSION 3
SHAPE     (4, 3, 2)
