In [ ]:
# installing the numpy
!pip install numpy

In [1]:
# importing numpy

import numpy as np  # package can be called using "np" as its alias

In [ ]:
# list to numpy array

lst = ['abc', 'def', 'ghi', 'jkl']

arr = np.array(lst)

print(type(arr))
print(arr)

<class 'numpy.ndarray'>
['abc' 'def' 'ghi' 'jkl']


In [ ]:
# arrays

# arrays is of homogenous structure, will only contain the same datatype
# list with different datatype elements will be converted to same type
# same type will be determined by the possible datatype that all the elements of list can adapt
# the shape of the array is not changeable after initialization

lst = [1,2,3,4,'a','b']   # lst contains int and string data types

arr = np.array(lst)       # changing to array will conver int into string because we cant cast string into int

print(type(arr))
print(arr)
print(type(arr[1]))

<class 'numpy.ndarray'>
['1' '2' '3' '4' 'a' 'b']
<class 'numpy.str_'>


In [ ]:
# numpy.array()

# numpy.array can create a array from list or tuple
# numpy.array will call the __array__() method in the class for the user defiend objects
# if we create __array__() in our class, then when calling numpy.array(ourobject) it will call the method __array__() of our object
# list and tuple doesn't have __array__() method but numpy.array() internally handle list and tuple to give array

In [ ]:
# ndarray.tolist()

# is used to convert the ndarray to python list
print(type(arr))
print(arr)
lst = arr.tolist()
print()
print(type(lst))
print(lst)

<class 'numpy.ndarray'>
['1' '2' '3' '4' 'a' 'b']

<class 'list'>
['1', '2', '3', '4', 'a', 'b']


In [ ]:
# datatype

# array has multiple datatype even for a integer datatype

lst = [1,2,3, 4, 5]

arr = np.array(lst)

print(arr)
print(type(arr[1]))

# We can change the datatype of element from int64 to other datatype like int8
print("Converting int64 datatype into int8 datatype")

arr1 = np.array(lst, dtype = np.int8)

print(arr1)
print(type(arr1[1]))

arr2 = np.array(lst, dtype = np.float64)

print(arr2)
print(type(arr2[1]))

[1 2 3 4 5]
<class 'numpy.int64'>
Converting int64 datatype into int8 datatype
[1 2 3 4 5]
<class 'numpy.int8'>
[1. 2. 3. 4. 5.]
<class 'numpy.float64'>


In [ ]:
# numpy.arange(start, stop, step)

# similar to range() function
# returns ndarray type

arr = np.arange(1,10,2)

print(arr)
print(type(arr))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [ ]:
# np.linspace(start, stop, num = x)

# linspace will give x number of equally spaced numbers between start and stop point
# returns the ndarray of float elements

arr = np.linspace(1,10,5)
print(arr)

print(arr[1]-arr[0])
print(arr[2]-arr[1])
print(arr[3]-arr[2])
print(arr[4]-arr[3])


[ 1.    3.25  5.5   7.75 10.  ]
2.25
2.25
2.25
2.25


In [ ]:
# 1 DIMENSIONAL ARRAY OR LIST

# [1, 2, 3, 4, 5]

# 2 DIMENSIONAL ARRAY OR LIST

# [[1, 2, 3], [4, 5, 6], [7, 8, 9]]        OR     [[1, 2, 3],
#                                                  [4, 5, 6],
#                                                  [7, 8, 9]]

# 3 DIMENSION ARRAY OR LIST

# [[[1, 2, 3], [4,5]],[6,7,8]]  OR     [[[1, 2, 3],
#                                         [4,5]],
#                                         [6, 7, 8]]


In [ ]:
# numpy.zeros(shape, dtype)

# this function will create a ndarray of zeros in dimension shape of shape paramenter
# the elements will be in float by default

print(np.zeros(5))
print()
dim3 = np.zeros((4,3,2))
print(dim3)

print()
print("DIMENSION",dim3.ndim)   # used to find the dimension of the ndarray
print("SHAPE    ",dim3.shape)  # used to find the shape of the ndarray

[0. 0. 0. 0. 0.]

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]

DIMENSION 3
SHAPE     (4, 3, 2)


In [ ]:
# numpy.ones(shape, dtype)

# this function will create a ndarray of one in dimension of shape paramenter
# the elements will be in float by default

print(np.ones(5))
print()
dim3 = np.ones((4,3,2), dtype = np.int8)
print(dim3)

print()
print("DIMENSION",dim3.ndim)   # used to find the dimension of the ndarray
print("SHAPE    ",dim3.shape)  # used to find the shape of the ndarray

[1. 1. 1. 1. 1.]

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]

DIMENSION 3
SHAPE     (4, 3, 2)


In [ ]:
# numpy.full(shape, fill_value, dtype)

# this function will create a ndarray of fill_value parameter in dimension of shape paramenter

print(np.full(5, 10.0))
print()
dim3 = np.full((4,3,2), 7, dtype = np.int8)
print(dim3)

print()
print("DIMENSION",dim3.ndim)   # used to find the dimension of the ndarray
print("SHAPE    ",dim3.shape)  # used to find the shape of the ndarray

[10. 10. 10. 10. 10.]

[[[7 7]
  [7 7]
  [7 7]]

 [[7 7]
  [7 7]
  [7 7]]

 [[7 7]
  [7 7]
  [7 7]]

 [[7 7]
  [7 7]
  [7 7]]]

DIMENSION 3
SHAPE     (4, 3, 2)


In [ ]:
# identity matrix

# diagonals with one

#  1 0 0 0
#  0 1 0 0
#  0 0 1 0
#  0 0 0 1

In [ ]:
# numpy.eye(n, m, k) -> n - rows, m - columns, k - diagonal index

# creates the identity matrix of size dim
# will creates the n X n if only one parameter is given
# k will define the start of the diagonal of 1, positive value will give upper diagonal and negative will give lower diagonal
# default element datatype is float

print(np.eye(4))
print()
print(np.eye(3,4))
print()
print(np.eye(4, 4, -2))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [ ]:
# numpy.empty(shape)

# provides the empty ndarray of dimension shape
# here the ndarray will only be allocate with difined shape of array where only the memory for the array is allcated
# it will not initialize with the elements or anything
# the values of the array that are displayed are garbage values which is already present in the allocated memory

print(np.empty(5))
print()
dim3 = np.empty((2,3,4))
print(dim3)
print()
dim2 = np.empty((2,3) ,dtype=int)
print(dim2)

[10. 10. 10. 10. 10.]

[[[5.e-324 5.e-324 5.e-324 5.e-324]
  [5.e-324 5.e-324 5.e-324 5.e-324]
  [5.e-324 5.e-324 5.e-324 5.e-324]]

 [[5.e-324 5.e-324 5.e-324 5.e-324]
  [5.e-324 5.e-324 5.e-324 5.e-324]
  [5.e-324 5.e-324 5.e-324 5.e-324]]]

[[0 0 0]
 [0 0 0]]


In [ ]:
# numpy.randam.rand(shape)

# provides the random values of dimension shape
# the random value will be between 0 and 1

print(np.random.rand(5, ))
print()
dim3 = np.random.rand(2,3,4)
print(dim3)

# we can change by mulitplying with 10s or 100s
print()
print(np.random.rand(5)*10)

[0.16476794 0.57659461 0.74658407 0.66209116 0.32676826]

[[[0.87921456 0.7575868  0.78685271 0.26513792]
  [0.22991996 0.62977926 0.2015153  0.36951759]
  [0.76815321 0.13665891 0.19017954 0.41239044]]

 [[0.39000125 0.08928057 0.21380692 0.29387365]
  [0.4825293  0.80488787 0.616539   0.42163625]
  [0.07195883 0.04026651 0.22788443 0.13324636]]]

[9.77559475 4.41424299 8.7234431  8.54589813 4.27964493]


In [ ]:
# ndarray attributes

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

print("SHAPE   ",arr.shape)  # gives the shape of the array
print("DIM     ",arr.ndim)   # gives the dimension
print("DTYPE   ",arr.dtype)  # gives the datatype of elements of array
print("SIZE    ",arr.size)   # gives the no. of elements in array
print("ITEMSIZE",arr.itemsize) # gives the bytes size of a single element of array
print("TOTAL BYTES",arr.nbytes)  # gives the bytes size of whole array (size x itemsize)
print("TRANSPOSE\n",arr.T)   # gives the transpose of array (transpose - rows are converted to columns and columns are converted into rows)

[[1 2 3]
 [4 5 6]]
SHAPE    (2, 3)
DIM      2
DTYPE    int64
SIZE     6
ITEMSIZE 8
TOTAL BYTES 48
TRANSPOSE
 [[1 4]
 [2 5]
 [3 6]]


In [ ]:
# indexing and slicing

# this works same as the python list

arr = np.array([10, 20, 30, 40, 50, 60])

print(arr[1:4])
print(arr[1:4:2])
print(arr[::-1])

[20 30 40]
[20 40]
[60 50 40 30 20 10]


In [ ]:
# with 2 dimensional array

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)
print()
print(arr2[1,2])
print(arr2[:,2])
print(arr2[:2,1:])
print()
print(arr2[::-1,::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

6
[3 6 9]
[[2 3]
 [5 6]]

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [ ]:
# boolean indexing

arr = np.array([5, 10, 15, 20, 25])

print(arr>10)       # return a list of boolean
print(arr[arr>10])  # indexing using the condition or boolean values

lst = [2,4]
print(arr[lst])     # the element of lst is consider as index

[False False  True  True  True]
[15 20 25]
[15 25]


In [ ]:
# numpy.where(condition)

# gives the index of the element where the condition iside the where function is satisfied

arr = np.array([5, 10, 15, 20, 25])
ind = np.where(arr>10)
print("INDEX WHERE arr>10 ", ind)
print()
print(arr[ind])   # getting the values using the index which is accuried by where() function

INDEX WHERE arr>10  (array([2, 3, 4]),)

[15 20 25]


In [ ]:
# array resizing and reshaping

In [ ]:
# ndarray.reshape()

# used to reshape the list for example changing the dimension of the array

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

print(arr.size)

new_arr = arr.reshape(4,2)
print()
print(new_arr)

8

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# reshaping without providing all the shape values
# if mentioned -1, it will auto create the shape with respect to other given parameter
# eg: only row dim can be given and the reshape will auto create list if -1 is mentioned in 2nd argument

new_arr = arr.reshape(2, -1)
print(new_arr)

print("_______________\n")

print(arr.reshape(2, 2, -1))

print("_______________\n")

print(arr.reshape(-1, 2))

[[1 2 3 4]
 [5 6 7 8]]
_______________

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
_______________

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
# ndarray.flatten()

# will convert any dimensional into a single dimensional array

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr_3 = arr.reshape(-1, 2, 2)

print(arr_3)

print("_______________\n")

arr_1 = arr_3.flatten()
print(arr_1)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
_______________

[1 2 3 4 5 6 7 8]


In [ ]:
# ndarray.resize(dim) -> returns None (directly changes the arr)

# resize will change the dimension of the arr just like reshape
# but resize will not through error if the no. of element and the new dimensional of the arr is not match
# resize will add 0 for if the given dimension size is larger than the no of elements
# and will truncate the elements if the dimension is smaller than the no. of elements

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr.resize(4,3)

print(arr)

print("_______________\n")

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr.resize(2, 2)
print(arr)


[[1 2 3]
 [4 5 6]
 [7 8 0]
 [0 0 0]]
_______________

[[1 2]
 [3 4]]


In [ ]:
# numpy.squeeze(arr, axis:None or int or tuple of int)

# used to degrade the dimension of the multi dimensional array
# remove axes of length one from a
# axes or axis here refers to the level of dimension or shape ie., 3 dim array has 3 axis likewise 2 dim array has 2 axis
# squeeze will remove all the axis or the level of dimension, if the particular level or axis is of length 1

arr = np.array([[[1],[2],[3],[4],[5],[6]],[[1],[2],[3],[4],[5],[6]]])

print("OLD SHAPE   ",arr.shape)       # shape = (2,6,1)  hence the axis of 0 = 2, axis of 1 = 6, axis of 2 = 1

# squeeze will remove the levels if the length is 1, i.e,. the above arr will be squeezed into of shape = (2,6)
# we can specify the level to squeeze by providing the axis, in above case axis = 2. multiple access can be squeezed by passing tuple to axis parameter
# if the axis is of not length then the squeeze will through error

print("_______________\n")

squeezed = np.squeeze(arr, axis=2)  # squeezing with respect to axis 1, because only axis 1 has the length of 1 elements

print("NEW SHAPE   ",squeezed.shape)
print(squeezed)

OLD SHAPE    (2, 6, 1)
_______________

NEW SHAPE    (2, 6)
[[1 2 3 4 5 6]
 [1 2 3 4 5 6]]


In [ ]:
# numpy.sum(arr, axis)

# gives sum of array elements for the given axis

arr = np.array([[[1, 2, 3], [4, 5, 6]],[[1, 2, 3], [4, 5, 6]]])

print(arr.shape)

print(np.sum(arr))
print(np.sum(arr, axis=0))
print("_______________\n")
print(np.sum(arr, axis=1))
print("_______________\n")
print(np.sum(arr, axis=2))
print("_______________\n")
print(arr)

(2, 2, 3)
42
[[ 2  4  6]
 [ 8 10 12]]
_______________

[[5 7 9]
 [5 7 9]]
_______________

[[ 6 15]
 [ 6 15]]
_______________

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
# for greater understanding of axis

# shape = (axis_1, axis_2, axis_3)
# shape = (z, y, x)

# the axis x(0) will always starts from right and y moves to left in the ndarray.shape

In [ ]:
# numpy math operation

# numpy is capable of performing vectorised math operation

lst = [1,2,3]
lst1 = [4,5,6]

print("python list addition   ",lst+lst1)

arr = np.array([1,2,3])
arr1 = np.array([4,5,6])

print("numpy array addition   ",arr+arr1)    # can perform the vector addition

python list addition    [1, 2, 3, 4, 5, 6]
numpy array addition    [5 7 9]


In [ ]:
print("Numpy array Subtraction:  ", arr1-arr)

Numpy array Subtraction:   [3 3 3]


In [ ]:
# broadcasting rules

# w.k.t for matrix addition and substraction both the matix dimension has to be same  (shape(3,4) added with shape(3,4))

# but numpy can perform addition and multiplication even if the above contidion is not satisfied
# numpy can perform math operation if the above condition or if their shapes are compatible via broadcasting.
# numpy performs broadcasting on one of the matrix to match the other matrix shape with the above condition

# Two dimensions are compatible under the broadcasting rule when:
#   They are equal, or
#   One of them is 1

# if any of the either matirx's dimension is 1 then numpy will replicate other elements to match the other matrix
# eg
# ShapeA = (3,4) and ShapeB = (1,4)  here numpy ShapeB is broadcasted to ShapeB = (3,4) by copy the elements to other rows
# ShapeA = (6,4) and ShapeB = (2,4)  here none of the matrix has 1 in the shape so the adition will throw ValueError
# ShapeA = (3,1,5) and ShapeB = (1,3,1) here both A and B can be broadcasted to match ShapeA = (3,3,5) and ShapeB = (3,3,5)

# braodcast rule will be applicable for all the operations like
#   arithematic operation (+, -, *, /, //, %, **)  | note: '*' won't work like actual matrix multiplication
#   comparision operation (==, !=, <, >, <=, >=)
#   logical operation (np.logical_and, np.logical_or, np.logical_not, etc.)
#   bitwise operation (&, |, ^, ~)
#   universal operation (np.sin, np.exp, np.sqrt, np.maximum, etc.)

# Operations that do NOT use broadcasting:
# Matrix multiplication
#   np.dot, @, np.matmul follow matrix multiplication rules, not broadcasting.
#   However, np.matmul does support broadcasting of batch dimensions.
# Reduction operations
#   Like np.sum, np.mean, np.max, etc., operate along specified axes and don’t broadcast across arrays.

In [ ]:
lst = [[[1],[2],[3]]]
lst1 = [4,5,6]

arr = np.array(lst)
arr1 = np.array(lst1)

print(f"Shape_arr = {arr.shape} and Shape_arr1 = {arr1.shape}")

# here shape_arr1 will be padded to make the dimension same so shape_arr will became (1,1,3)
# now both the arrays can be broadcasted to match the other, finally shape_arr (1,3,3) and shape_arr1 will be (1,3,3)

print("numpy array addition   ",arr+arr1)

Shape_arr = (1, 3, 1) and Shape_arr1 = (3,)
numpy array addition    [[[5 6 7]
  [6 7 8]
  [7 8 9]]]


In [ ]:
# numpy array multiplication using '*' will work as matrix addition not like actual matrix multiplication where row is multiplied against columns
# even if the row of 1st and column of the second is matched it won't work like actual matrix multiplication

a = np.array([2,2,2])
b = np.array([[4],[5],[6]])

print(a*b)   # [2*4, 2*5, 2*6]

[[ 8  8  8]
 [10 10 10]
 [12 12 12]]


In [ ]:
# comparison operator on numpy array

a = np.array([4,7,12])
b = np.array([5,3,20])

print(a>b)
print(a==b)
print(a!=b)

[False  True False]
[False False False]
[ True  True  True]


In [ ]:
# logical operators on numpy array

a = np.array([1,1,0]) # here we can also use [True, True, False]
b = np.array([1,0,1])

print(np.logical_and(a,b))
print(np.logical_or(a,b))
print(np.logical_not(a))

[ True False False]
[ True  True  True]
[False False  True]


In [ ]:
# bitwise operators on numpy array

a = np.array([1, 2, 3])
b = np.array([3, 2, 1])

print(a&b, np.bitwise_and(a,b))
print(a|b, np.bitwise_or(a,b))
print(a^b, np.bitwise_xor(a,b))
print(~a, np.bitwise_not(a))

[1 2 1] [1 2 1]
[3 2 3] [3 2 3]
[2 0 2] [2 0 2]
[-2 -3 -4] [-2 -3 -4]


In [ ]:
# common math function with numpy array

a = np.array([1,2,3,4])

print(np.sqrt(a))
print(np.exp(a))
print(np.log(a))
print(np.sin(a))

[1.         1.41421356 1.73205081 2.        ]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [ ]:
# aggregation funcition with numpy array

a = np.array([[1,2,3],[4,5,6]])

print(np.sum(a))
print(np.mean(a))
print(np.std(a))
print(np.min(a))
print(np.max(a))

21
3.5
1.707825127659933
1
6


In [ ]:
# matrix multiplication or dot product with numpy array

# for matrix multiplication assume of matrix A of size MxN and matrix of B of size PxQ
# condition: column of matrix A(N) and row of matrix B(P) must have to be same(N==P)
# the resultant matrix will be of size of row of matrix A(M) and column of matrix B(Q) which is (MxQ)

# A = { a11   a12       and   B = { b11  b12
#       a21   a22 }                 b21  b22 }
#
# then,
# A.B or AxB = { (a11*b11)+(a12*b21)  (a11*b12)+(a12*b22)
#                (a21*b11)+(a22*b21)  (a21*b12)+(a22*b22)  }

In [ ]:
# Transopsing the numpy array

a = np.array([[1, 11],[2, 12],[3, 13]])

print(a)
print(a.T)

[[ 1 11]
 [ 2 12]
 [ 3 13]]
[[ 1  2  3]
 [11 12 13]]


In [ ]:
# dot product

# using dot product : numpy.dot(A, B) or (A @ B) or numpy.matmul()

a = np.array([[1, 11],[2, 12],[3, 13]])
b = a.T

c = np.array([1,2,3])
d = np.array([4,5,6])

print(np.dot(a,b))
print()
print(np.dot(c,d))  # for single dimension array the numpy.dot() will automatically consider the 2nd (1,3) which single dimension matrix as (3,1) which is 2 dimensional matrix
                    # so the column of matrix c will match with row of matrix d

[[122 134 146]
 [134 148 162]
 [146 162 178]]

32


In [ ]:
# dot product is a combination of simple array multiplication and sum all the element in each row i.e., sum across column

c = np.array([1,2,3])
d = np.array([4,5,6])

mul = c * d   # this multiplication will not work if the broadcasting rule is not satisfied

print(mul)

print()
print(np.sum(mul))

[ 4 10 18]

32


In [ ]:
# numpy.dot() vs numpy.matmul()

# np.dot()
#    Inputs: (2, 3, 4) and (2, 4, 5)
#    Contracts:
#    Last axis of A (4)
#    Second-last axis of B (4)
#    Result shape: (2, 3, 2, 5)
#    No batch broadcasting — it performs a dot product for each pair of slices.

# np.matmul()
#    Inputs: (2, 3, 4) and (2, 4, 5)
#    Performs matrix multiplication on the last two dimensions:
#    (3, 4) @ (4, 5) → (3, 5)
#    Result shape: (2, 3, 5)
#    Supports batch broadcasting over the first dimension (2).
#
#    batch broadcasting over matmul()
#      If you have arrays A and B with shapes:
#        A.shape = (..., M, K)
#        B.shape = (..., K, N)
#        Then np.matmul(A, B) performs matrix multiplication on the last two dimensions (M × K and K × N) and broadcasts over the preceding dimensions (...).

In [ ]:
# numpy.matmul()

#  Input A has shape (2, 4, 5):
#   2 batches of 4×5 matrices

#  Input B has shape (2, 5, 3):
#   2 batches of 5×3 matrices

#  np.matmul(A, B) performs:
#   A[0] @ B[0] → (4×5) × (5×3) = (4×3)
#   A[1] @ B[1] → (4×5) × (5×3) = (4×3)

#  The result has shape (2, 4, 3) — one 4×3 matrix for each batch.

#  if the Input A has shape (1,4,5) and Input B has shape (2,5,3)
#  then the Input A shape (1,4,5) will be broadcasted into (2,4,5)

In [ ]:
print(np.matmul(c,d))

32


In [2]:
# numpy.vstack((arr, arr1))

# this will stack two arrays vertically

a = np.array([1,2])
b = np.array([3,4])

print(np.vstack((a,b)))

[[1 2]
 [3 4]]


In [3]:
# numpy.hstack((arr, arr1))

# this will stack two arrays horizontally

a = np.array([1,2])
b = np.array([3,4])

print(np.hstack((a,b)))

[1 2 3 4]


In [13]:
# numpy.char.<functions>()

# numpy has certain character operation which helps to work with array of string

a = np.array(['hello', 'WORLD'])
b = np.array(['_user', '666'])

print("String Concat    :", np.char.add(a, b))
print("String Multiply  :", np.char.multiply(a, 3))
print("String Upper     :", np.char.upper(a))
print("String Lower     :", np.char.lower(a))
print("String Capitalize:", np.char.capitalize(a))
print("String Split     :", np.char.split(a, "e"))
print("String Replace   :", np.char.replace(a, 'ello', 'i'))
print("String Join      :", np.char.join('-',a))
print("String Join      :", np.char.join(['-','*'],[a, b]))

String Concat    : ['hello_user' 'WORLD666']
String Multiply  : ['hellohellohello' 'WORLDWORLDWORLD']
String Upper     : ['HELLO' 'WORLD']
String Lower     : ['hello' 'world']
String Capitalize: ['Hello' 'World']
String Split     : [list(['h', 'llo']) list(['WORLD'])]
String Replace   : ['hi' 'WORLD']
String Join      : ['h-e-l-l-o' 'W-O-R-L-D']
String Join      : [['h-e-l-l-o' 'W*O*R*L*D']
 ['_-u-s-e-r' '6*6*6']]


In [5]:
# numpy.char.center(arr, length, fillchar)

# center will center the string where the total length is 'length' and fill the other slots of length with the 'fillchar'
# center will padd the string at the center

a = np.array(['hello', 'world'])

print(np.char.center(a, 10, fillchar='*'))

['**hello***' '**world***']


In [15]:
# numpy.char.find()

# used to find the character or string from the array

a = np.array(['hello', 'world'])

print(np.char.find(a, 'e'))

[ 1 -1]


In [19]:
# numpy.char.count()

# used to count the number of character in the string of the array

print(np.char.count(a, 'l'))

[2 1]


In [24]:
# Statistical functions in numpy

a = np.array([[1,2,3,4,6]])

print(np.mean(a))     # mean  = average
print(np.median(a))   # median= middle value while the array is sorted
print(np.std(a))      # standard deviation
print(np.var(a))      # variation
print(np.min(a))      # minimum value
print(np.max(a))      # maximum value
print(np.argmax(a))   # index of maximum value
print(np.argmin(a))   # index of minimum value

# Note : this functions can also be calculated along the particular axis

3.2
3.0
1.7204650534085253
2.96
1
6
4
0


In [ ]:
# percentage vs percentile

# percentage - is the percentage of the single person, it doesn't depend on other values other
# percentile - is used to defiend the no. of elements or values fall under that percentile number

a = np.array([4.5, 5.7, 8.9, 9.0, 9.8])   # marks out of 10

# percentage = [45%, 57%, 89%, 90%, 98%]  it depends on it own doesn't need to be a group or array
# percentile = [4.5, 5.7] is 40 percentile of the a or marks i.e., in array 'a', [4.5, 5.7] are the elements that are fall under 40 percentile of the whole array

In [28]:
# percentile and quantile

# numpy.percentile(arr, q) == numpy.quantile(arr, q/100)  # this equation is mathematically came

a = np.array([1,3,5,7,9])

print(np.percentile(a, 50)) # will give the median which is the middle (50th percent of whole data)
print(np.quantile(a, 0.5))  # quantile is the same as percentile but the 2nd argument we mention will be 0 to 1

5.0
5.0


In [35]:
# search, sort

a = np.array([1, 2, 3, 2, 5, 1, 8, 4, 6])

print("Sorted  :"                  , np.sort(a))
print("Index in ascending manner :", np.argsort(a))
print("search :"                   ,np.searchsorted(a, 7))  # will give the position where the order of sorted element won't change if we inserted the given value
                                          # if a is sorted if we insert 7 at the 9th(searchsort() returned) position or index the sorted order of 'a' will not collapse
                                          # the input array needs to be sorted to get correct value
print("Search Sort : "            , np.searchsorted(np.sort(a), 5.5))

Sorted  : [1 1 2 2 3 4 5 6 8]
Index in ascending manner : [0 5 3 1 2 7 4 8 6]
search : 9
Search Sort : 7


In [36]:
# numpy.unique()
# gives all the unique element of the given array

print(np.unique(a))

[1 2 3 4 5 6 8]


In [37]:
# numpy.bincount(arr)

# it will get the max number of the array
# and count all the number persent in the list starting from 0 to the max number of the array
# if max = 8, the bincount will return the count of 0, 1, 2, 3, 4, 5, 6, 7, 8

print(np.bincount(a))

# output = [0 2 2 1 1 1 1 0 1]
# explain= array has 0 - 0's, 2 - 1's, 2 - 3's, 1 - 4's till 0 - 7's and 1 - 8's

[0 2 2 1 1 1 1 0 1]


In [38]:
# iteration over numpy array

arr = np.arange(8).reshape(2,2,2)
arr1 = np.arange(6).reshape(3,2)

for i in arr:
  print(i)

print()

for i in arr1:
  print(i)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]

[0 1]
[2 3]
[4 5]


In [39]:
# numpy.nditer(arr)

# if will iter all the element one by one indefinite of the dimension

for i in np.nditer(arr):
  print(i)

0
1
2
3
4
5
6
7


In [45]:
# numpy.copy()

# if the array is assigned to other variable there will be no new memory the new variable will also point to the original memory of array
# it will cause the change in original array if we change or alter the new variable
# its because dtype like list and ndarray won't create the values in new memory but just point the variable to the original values's memory

# using numpy.copy() will create a copy of elements with the new memory and alloted space
# so, it won't affect original or old array if we alter the array using new variable

a = np.array([1,2,3])
b = a
b[0] = 100
print("a :",a)    # 'a' is changed by altering b[0]

a = np.array([1,2,3])
b = a.copy()
b[0] = 99
print("b :",b)
print("a :",a)


a : [100   2   3]
b : [99  2  3]
a : [1 2 3]


In [63]:
# ndarray.ravel()

# ravel is similar to flatten() function which will convert the n dimarray into 1 dimarray
# but ravel will share the memory of the original array, while flatten will create new memory for the object

a = np.arange(6).reshape(2,3)
print(a)

rav = a.ravel()   # ravel will create a view of the original array and return as single dimensional array(memory is shared)
                  # while flatten() will create a copy(memory doesn't shared)
print()
print(rav)
rav[1] = 20
print()

print(a)

[[0 1 2]
 [3 4 5]]

[0 1 2 3 4 5]

[[ 0 20  2]
 [ 3  4  5]]


In [66]:
# view

# view is a concept of database, where the original data is slicied and stored in a new variable but the memorys of those elements are same

a = np.arange(5)

b = a[1:4]  # creating the view of the array

print(a)
print(b)

[0 1 2 3 4]
[1 2 3]
