In [ ]:
# installing the numpy
!pip install numpy

In [2]:
# importing numpy

import numpy as np  # package can be called using "np" as its alias

In [3]:
# list to numpy array

lst = ['abc', 'def', 'ghi', 'jkl']

arr = np.array(lst)

print(type(arr))
print(arr)

<class 'numpy.ndarray'>
['abc' 'def' 'ghi' 'jkl']


In [53]:
# arrays

# arrays is of homogenous structure, will only contain the same datatype
# list with different datatype elements will be converted to same type
# same type will be determined by the possible datatype that all the elements of list can adapt
# the shape of the array is not changeable after initialization

lst = [1,2,3,4,'a','b']   # lst contains int and string data types

arr = np.array(lst)       # changing to array will conver int into string because we cant cast string into int

print(type(arr))
print(arr)
print(type(arr[1]))

<class 'numpy.ndarray'>
['1' '2' '3' '4' 'a' 'b']
<class 'numpy.str_'>


In [54]:
# ndarray.tolist()

# is used to convert the ndarray to python list
print(type(arr))
print(arr)
lst = arr.tolist()
print()
print(type(lst))
print(lst)

<class 'numpy.ndarray'>
['1' '2' '3' '4' 'a' 'b']

<class 'list'>
['1', '2', '3', '4', 'a', 'b']


In [10]:
# datatype

# array has multiple datatype even for a integer datatype

lst = [1,2,3, 4, 5]

arr = np.array(lst)

print(arr)
print(type(arr[1]))

# We can change the datatype of element from int64 to other datatype like int8
print("Converting int64 datatype into int8 datatype")

arr1 = np.array(lst, dtype = np.int8)

print(arr1)
print(type(arr1[1]))

arr2 = np.array(lst, dtype = np.float64)

print(arr2)
print(type(arr2[1]))

[1 2 3 4 5]
<class 'numpy.int64'>
Converting int64 datatype into int8 datatype
[1 2 3 4 5]
<class 'numpy.int8'>
[1. 2. 3. 4. 5.]
<class 'numpy.float64'>


In [13]:
# numpy.arange(start, stop, step)

# similar to range() function
# returns ndarray type

arr = np.arange(1,10,2)

print(arr)
print(type(arr))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [15]:
# np.linspace(start, stop, num = x)

# linspace will give x number of equally spaced numbers between start and stop point
# returns the ndarray of float elements

arr = np.linspace(1,10,5)
print(arr)

print(arr[1]-arr[0])
print(arr[2]-arr[1])
print(arr[3]-arr[2])
print(arr[4]-arr[3])


[ 1.    3.25  5.5   7.75 10.  ]
2.25
2.25
2.25
2.25


In [ ]:
# 1 DIMENSIONAL ARRAY OR LIST

# [1, 2, 3, 4, 5]

# 2 DIMENSIONAL ARRAY OR LIST

# [[1, 2, 3], [4, 5, 6], [7, 8, 9]]        OR     [[1, 2, 3],
#                                                  [4, 5, 6],
#                                                  [7, 8, 9]]

# 3 DIMENSION ARRAY OR LIST

# [[[1, 2, 3], [4,5]],[6,7,8]]  OR     [[[1, 2, 3],
#                                         [4,5]],
#                                         [6, 7, 8]]


In [26]:
# numpy.zeros(shape, dtype)

# this function will create a ndarray of zeros in dimension shape of shape paramenter
# the elements will be in float by default

print(np.zeros(5))
print()
dim3 = np.zeros((4,3,2))
print(dim3)

print()
print("DIMENSION",dim3.ndim)   # used to find the dimension of the ndarray
print("SHAPE    ",dim3.shape)  # used to find the shape of the ndarray

[0. 0. 0. 0. 0.]

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]

DIMENSION 3
SHAPE     (4, 3, 2)


In [31]:
# numpy.ones(shape, dtype)

# this function will create a ndarray of one in dimension of shape paramenter
# the elements will be in float by default

print(np.ones(5))
print()
dim3 = np.ones((4,3,2), dtype = np.int8)
print(dim3)

print()
print("DIMENSION",dim3.ndim)   # used to find the dimension of the ndarray
print("SHAPE    ",dim3.shape)  # used to find the shape of the ndarray

[1. 1. 1. 1. 1.]

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]

DIMENSION 3
SHAPE     (4, 3, 2)


In [40]:
# numpy.full(shape, fill_value, dtype)

# this function will create a ndarray of fill_value parameter in dimension of shape paramenter

print(np.full(5, 10.0))
print()
dim3 = np.full((4,3,2), 7, dtype = np.int8)
print(dim3)

print()
print("DIMENSION",dim3.ndim)   # used to find the dimension of the ndarray
print("SHAPE    ",dim3.shape)  # used to find the shape of the ndarray

[10. 10. 10. 10. 10.]

[[[7 7]
  [7 7]
  [7 7]]

 [[7 7]
  [7 7]
  [7 7]]

 [[7 7]
  [7 7]
  [7 7]]

 [[7 7]
  [7 7]
  [7 7]]]

DIMENSION 3
SHAPE     (4, 3, 2)


In [ ]:
# identity matrix

# diagonals with one

#  1 0 0 0
#  0 1 0 0
#  0 0 1 0
#  0 0 0 1

In [38]:
# numpy.eye(n, m, k) -> n - rows, m - columns, k - diagonal index

# creates the identity matrix of size dim
# will creates the n X n if only one parameter is given
# k will define the start of the diagonal of 1, positive value will give upper diagonal and negative will give lower diagonal
# default element datatype is float

print(np.eye(4))
print()
print(np.eye(3,4))
print()
print(np.eye(4, 4, -2))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


In [50]:
# numpy.empty(shape)

# provides the empty ndarray of dimension shape
# here the ndarray will only be allocate with difined shape of array where only the memory for the array is allcated
# it will not initialize with the elements or anything
# the values of the array that are displayed are garbage values which is already present in the allocated memory

print(np.empty(5))
print()
dim3 = np.empty((2,3,4))
print(dim3)
print()
dim2 = np.empty((2,3) ,dtype=int)
print(dim2)

[10. 10. 10. 10. 10.]

[[[5.e-324 5.e-324 5.e-324 5.e-324]
  [5.e-324 5.e-324 5.e-324 5.e-324]
  [5.e-324 5.e-324 5.e-324 5.e-324]]

 [[5.e-324 5.e-324 5.e-324 5.e-324]
  [5.e-324 5.e-324 5.e-324 5.e-324]
  [5.e-324 5.e-324 5.e-324 5.e-324]]]

[[0 0 0]
 [0 0 0]]


In [52]:
# numpy.randam.rand(shape)

# provides the random values of dimension shape
# the random value will be between 0 and 1

print(np.random.rand(5, ))
print()
dim3 = np.random.rand(2,3,4)
print(dim3)

# we can change by mulitplying with 10s or 100s
print()
print(np.random.rand(5)*10)

[0.16476794 0.57659461 0.74658407 0.66209116 0.32676826]

[[[0.87921456 0.7575868  0.78685271 0.26513792]
  [0.22991996 0.62977926 0.2015153  0.36951759]
  [0.76815321 0.13665891 0.19017954 0.41239044]]

 [[0.39000125 0.08928057 0.21380692 0.29387365]
  [0.4825293  0.80488787 0.616539   0.42163625]
  [0.07195883 0.04026651 0.22788443 0.13324636]]]

[9.77559475 4.41424299 8.7234431  8.54589813 4.27964493]


In [68]:
# ndarray attributes

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

print("SHAPE   ",arr.shape)  # gives the shape of the array
print("DIM     ",arr.ndim)   # gives the dimension
print("DTYPE   ",arr.dtype)  # gives the datatype of elements of array
print("SIZE    ",arr.size)   # gives the no. of elements in array
print("ITEMSIZE",arr.itemsize) # gives the bytes size of a single element of array
print("TOTAL BYTES",arr.nbytes)  # gives the bytes size of whole array (size x itemsize)
print("TRANSPOSE\n",arr.T)   # gives the transpose of array (transpose - rows are converted to columns and columns are converted into rows)

[[1 2 3]
 [4 5 6]]
SHAPE    (2, 3)
DIM      2
DTYPE    int64
SIZE     6
ITEMSIZE 8
TOTAL BYTES 48
TRANSPOSE
 [[1 4]
 [2 5]
 [3 6]]


In [69]:
# indexing and slicing

# this works same as the python list

arr = np.array([10, 20, 30, 40, 50, 60])

print(arr[1:4])
print(arr[1:4:2])
print(arr[::-1])

[20 30 40]
[20 40]
[60 50 40 30 20 10]


In [77]:
# with 2 dimensional array

arr2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)
print()
print(arr2[1,2])
print(arr2[:,2])
print(arr2[:2,1:])
print()
print(arr2[::-1,::-1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

6
[3 6 9]
[[2 3]
 [5 6]]

[[9 8 7]
 [6 5 4]
 [3 2 1]]


In [81]:
# boolean indexing

arr = np.array([5, 10, 15, 20, 25])

print(arr>10)       # return a list of boolean
print(arr[arr>10])  # indexing using the condition or boolean values

lst = [2,4]
print(arr[lst])     # the element of lst is consider as index

[False False  True  True  True]
[15 20 25]
[15 25]


In [86]:
# numpy.where(condition)

# gives the index of the element where the condition iside the where function is satisfied

arr = np.array([5, 10, 15, 20, 25])
ind = np.where(arr>10)
print("INDEX WHERE arr>10 ", ind)
print()
print(arr[ind])   # getting the values using the index which is accuried by where() function

INDEX WHERE arr>10  (array([2, 3, 4]),)

[15 20 25]
